name: aifit_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.2+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  freezed_annotation:
  json_annotation: ^4.9.0
  cloud_firestore: ^5.5.1
  flutter_hooks:
  go_router: ^14.6.1
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  pluto_grid_plus:
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner:
  custom_lint:
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true


